### ISSUE TITLE
TODO: pre-install node_modules for godwoken-web3

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken-docker-prebuilds#2]
```
  "workspaces": [
    "packages/*"
  ],
```
All workspaces's package.json should be copied into container.
[This `yarn install` ](https://github.com/nervosnetwork/godwoken-docker-prebuilds/blob/0ef272c081f8500f6f7389b5b429b03f559da48e/Dockerfile#L40-L42) is not enough.

**Comment by jjyr** [comment]
IMO we should make a standalone docker image for godwoken-web3.

The web3 service does not need to read binaries, and the node dependencies will increase the docker image size, so we should use the prebuild-image only for godwoken binaries, and use another image for web3.

**Comment by Flouse** [comment]
> IMO we should make a standalone docker image for godwoken-web3.

This is a better way. 
[PR: init Dockerfile for bitrocks/godwoken-web3 #42](https://github.com/bitrocks/godwoken-web3/pull/42) 

This Dockerfile is used in https://github.com/RetricSu/godwoken-kicker/pull/18
